"""Flight to airline Foreign Key

Revision ID: 19134990380f
Revises: 230e494a56d0
Create Date: 2025-08-10 18:45:18.305640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19134990380f'
down_revision: Union[str, None] = '230e494a56d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'flight', 'airlines', ['airline'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flight', type_='foreignkey')
    # ### end Alembic commands ###
