"""Modification of data type in flight

Revision ID: 230e494a56d0
Revises: c43fc8c85e0d
Create Date: 2025-08-10 18:33:56.719720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230e494a56d0'
down_revision: Union[str, None] = 'c43fc8c85e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flight', 'source_airport_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('flight', 'destination_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'flight', ['flight_code'])
    op.drop_constraint('flight_destination_id_fkey', 'flight', type_='foreignkey')
    op.drop_constraint('flight_source_airport_id_fkey', 'flight', type_='foreignkey')
    op.create_foreign_key(None, 'flight', 'airport', ['destination_id'], ['code'])
    op.create_foreign_key(None, 'flight', 'airport', ['source_airport_id'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.create_foreign_key('flight_source_airport_id_fkey', 'flight', 'airport', ['source_airport_id'], ['id'])
    op.create_foreign_key('flight_destination_id_fkey', 'flight', 'airport', ['destination_id'], ['id'])
    op.drop_constraint(None, 'flight', type_='unique')
    op.alter_column('flight', 'destination_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('flight', 'source_airport_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
