"""Runway Foreign Key change

Revision ID: 30f69b0a5676
Revises: ffaafcef95ff
Create Date: 2025-08-09 13:06:52.119607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f69b0a5676'
down_revision: Union[str, None] = 'ffaafcef95ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runways', 'airport_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('runways_airport_id_fkey', 'runways', type_='foreignkey')
    op.create_foreign_key(None, 'runways', 'airport', ['airport_id'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runways', type_='foreignkey')
    op.create_foreign_key('runways_airport_id_fkey', 'runways', 'airport', ['airport_id'], ['id'])
    op.alter_column('runways', 'airport_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
