"""Gate table current_flight type change

Revision ID: 3d551feefbcf
Revises: c446bbcbf78b
Create Date: 2025-08-15 18:48:52.114113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d551feefbcf'
down_revision: Union[str, None] = 'c446bbcbf78b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baggage_belt', 'current_flight',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('baggage_belt_current_flight_fkey'), 'baggage_belt', type_='foreignkey')
    op.alter_column('gate', 'current_flight',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('gate_current_flight_fkey'), 'gate', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('gate_current_flight_fkey'), 'gate', 'flight', ['current_flight'], ['id'])
    op.alter_column('gate', 'current_flight',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_foreign_key(op.f('baggage_belt_current_flight_fkey'), 'baggage_belt', 'flight_instance', ['current_flight'], ['id'])
    op.alter_column('baggage_belt', 'current_flight',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
