"""Addition of airline to flight instance

Revision ID: 415c4c1edb01
Revises: 7bc613fba3b4
Create Date: 2025-08-15 17:29:31.412392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415c4c1edb01'
down_revision: Union[str, None] = '7bc613fba3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_instance', sa.Column('airline', sa.String(), nullable=True))
    op.create_foreign_key(None, 'flight_instance', 'airlines', ['airline'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flight_instance', type_='foreignkey')
    op.drop_column('flight_instance', 'airline')
    # ### end Alembic commands ###
