"""Addition of state in flight instance

Revision ID: 653a2e4c0cf0
Revises: 415c4c1edb01
Create Date: 2025-08-15 17:46:17.220240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653a2e4c0cf0'
down_revision: Union[str, None] = '415c4c1edb01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_instance', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight_instance', 'state')
    # ### end Alembic commands ###
