"""Minor changes1

Revision ID: 65646e5b96e9
Revises: 
Create Date: 2025-08-07 22:06:10.384127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65646e5b96e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('terminal', 'airport_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('terminal_airport_id_fkey', 'terminal', type_='foreignkey')
    op.create_foreign_key(None, 'terminal', 'airport', ['airport_id'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'terminal', type_='foreignkey')
    op.create_foreign_key('terminal_airport_id_fkey', 'terminal', 'airport', ['airport_id'], ['id'])
    op.alter_column('terminal', 'airport_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
