"""Addition of source and destination to flight instance

Revision ID: 7bc613fba3b4
Revises: 7d59e5a8f19d
Create Date: 2025-08-15 16:29:31.392935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc613fba3b4'
down_revision: Union[str, None] = '7d59e5a8f19d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_instance', sa.Column('source_airport_id', sa.String(), nullable=True))
    op.add_column('flight_instance', sa.Column('destination_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'flight_instance', 'airport', ['source_airport_id'], ['code'])
    op.create_foreign_key(None, 'flight_instance', 'airport', ['destination_id'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flight_instance', type_='foreignkey')
    op.drop_constraint(None, 'flight_instance', type_='foreignkey')
    op.drop_column('flight_instance', 'destination_id')
    op.drop_column('flight_instance', 'source_airport_id')
    # ### end Alembic commands ###
