"""Flight columns update

Revision ID: 7d59e5a8f19d
Revises: 810153b00bce
Create Date: 2025-08-10 21:35:35.759028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d59e5a8f19d'
down_revision: Union[str, None] = '810153b00bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('recurring', sa.Boolean(), nullable=True))
    op.drop_column('flight', 'reccuring')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('reccuring', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('flight', 'recurring')
    # ### end Alembic commands ###
