"""Addition of base to airport_airport_type

Revision ID: 7ecb5f06af56
Revises: a875a0f305c8
Create Date: 2025-07-29 22:31:10.635240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ecb5f06af56'
down_revision: Union[str, None] = 'a875a0f305c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airport_airport_type',
    sa.Column('airport_id', sa.UUID(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airport.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['airport_type.id'], ),
    sa.PrimaryKeyConstraint('airport_id', 'type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('airport_airport_type')
    # ### end Alembic commands ###
