"""Flight columns update

Revision ID: 810153b00bce
Revises: 19134990380f
Create Date: 2025-08-10 21:22:30.085786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '810153b00bce'
down_revision: Union[str, None] = '19134990380f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('reccuring', sa.Boolean(), nullable=True))
    op.add_column('flight', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight', 'is_active')
    op.drop_column('flight', 'reccuring')
    # ### end Alembic commands ###
