"""Addition of is_active in Terminal

Revision ID: b06f1838cd0d
Revises: 8b3b16371624
Create Date: 2025-08-10 11:25:26.711318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06f1838cd0d'
down_revision: Union[str, None] = '8b3b16371624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terminal', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terminal', 'is_active')
    # ### end Alembic commands ###
