"""Addition of number in Gate

Revision ID: c43fc8c85e0d
Revises: b06f1838cd0d
Create Date: 2025-08-10 18:15:11.199984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43fc8c85e0d'
down_revision: Union[str, None] = 'b06f1838cd0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gate', sa.Column('number', sa.String(), nullable=True))
    op.create_unique_constraint('uix_gate_number_terminal_id', 'gate', ['number', 'terminal_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_gate_number_terminal_id', 'gate', type_='unique')
    op.drop_column('gate', 'number')
    # ### end Alembic commands ###
