"""Addition of flight code to flight instance

Revision ID: c446bbcbf78b
Revises: 653a2e4c0cf0
Create Date: 2025-08-15 18:35:31.369724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c446bbcbf78b'
down_revision: Union[str, None] = '653a2e4c0cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('baggage_belt_current_flight_fkey'), 'baggage_belt', type_='foreignkey')
    op.create_foreign_key(None, 'baggage_belt', 'flight_instance', ['current_flight'], ['id'])
    op.add_column('flight_instance', sa.Column('flight_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight_instance', 'flight_code')
    op.drop_constraint(None, 'baggage_belt', type_='foreignkey')
    op.create_foreign_key(op.f('baggage_belt_current_flight_fkey'), 'baggage_belt', 'flight', ['current_flight'], ['id'])
    # ### end Alembic commands ###
