"""Runway status and active flag addition

Revision ID: ee3defb60851
Revises: 30f69b0a5676
Create Date: 2025-08-09 13:30:30.497494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee3defb60851'
down_revision: Union[str, None] = '30f69b0a5676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('airport', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('runways', sa.Column('status', sa.String(), nullable=True))
    op.add_column('runways', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('runways', 'airport_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runways', 'airport_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('runways', 'is_active')
    op.drop_column('runways', 'status')
    op.alter_column('airport', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
