"""Add number to BaggageBelt and unique constraint

Revision ID: f28a5dd7a569
Revises: ee3defb60851
Create Date: 2025-08-09 22:10:26.511426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f28a5dd7a569'
down_revision: Union[str, None] = 'ee3defb60851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baggage_belt', sa.Column('number', sa.Integer(), nullable=True))
    op.create_unique_constraint('uix_my_table_number_terminal_id', 'baggage_belt', ['number', 'terminal_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_my_table_number_terminal_id', 'baggage_belt', type_='unique')
    op.drop_column('baggage_belt', 'number')
    # ### end Alembic commands ###
