"""Initial clean migration

Revision ID: f475a31065b9
Revises: 7ecb5f06af56
Create Date: 2025-07-30 21:24:50.548060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f475a31065b9'
down_revision: Union[str, None] = '7ecb5f06af56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airline_staff', sa.Column('password', sa.String(), nullable=True))
    op.add_column('airport_staff', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airport_staff', 'password')
    op.drop_column('airline_staff', 'password')
    # ### end Alembic commands ###
