"""Minor changes

Revision ID: f936163bf1b7
Revises: f475a31065b9
Create Date: 2025-08-03 14:27:23.829412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f936163bf1b7'
down_revision: Union[str, None] = 'f475a31065b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gate', sa.Column('status', sa.String(), nullable=True))
    op.add_column('gate', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('gate', sa.Column('current_flight', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'gate', 'flight', ['current_flight'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gate', type_='foreignkey')
    op.drop_column('gate', 'current_flight')
    op.drop_column('gate', 'capacity')
    op.drop_column('gate', 'status')
    # ### end Alembic commands ###
