"""Fields Change

Revision ID: ffaafcef95ff
Revises: 65646e5b96e9
Create Date: 2025-08-09 11:14:20.990755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffaafcef95ff'
down_revision: Union[str, None] = '65646e5b96e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airportairlinemapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('airport', sa.String(), nullable=True),
    sa.Column('airline', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airport', 'airline', name='uix_my_table_airport_airline')
    )
    op.create_unique_constraint(None, 'airlines', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'airlines', type_='unique')
    op.drop_table('airportairlinemapping')
    # ### end Alembic commands ###
