from models import Airport
from database import db_session  # your SQLAlchemy session setup
from sqlalchemy.exc import SQLAlchemyError

def create_airport(data):
    """
    Creates a new airport using validated input data.
    """
    try:
        # Create the Airport object
        new_airport = Airport(
            name=data['name'],
            code=data['code'],
            location=data['location']
        )

        # Add to session and commit
        db_session.add(new_airport)
        db_session.commit()
        db_session.refresh(new_airport)  # To get autogenerated fields like id

        return new_airport

    except SQLAlchemyError as e:
        db_session.rollback()

def update_airport(airport_id, **kwargs):
    airport = db_session.query(Airport).filter_by(id=airport_id).first()
    if not airport:
        return None
    for key, value in kwargs.items():
        setattr(airport, key, value)
    db_session.commit()
    return airport

def get_airport_by_code(code):
    return db_session.query(Airport).filter_by(code=code).first()
